# Generated by Django 4.2.4 on 2023-08-25 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('owner', models.CharField(max_length=255, verbose_name='Responsable')),
                ('script', models.CharField(max_length=200, verbose_name='Fichero')),
            ],
        ),
        migrations.CreateModel(
            name='JobSchedule',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255, verbose_name='Nombre')),
                ('minute', models.CharField(default='*', help_text='Minutos donde se iniciará la ejecución. Deben ser números entre el 0 y el 59 separados por comas.', max_length=255, verbose_name='Minutos')),
                ('hour', models.CharField(default='*', help_text='Horas donde se iniciará la ejecución. Deben ser números entre el 0 y el 23 separados por comas.', max_length=255, verbose_name='Horas')),
                ('day_of_month', models.CharField(default='*', help_text='Días del mes donde se iniciará la ejecución. Deben ser números entre el 1 y el 31 (O la cantidad de día del mes) separados por comas.', max_length=255, verbose_name='Día del mes')),
                ('month', models.CharField(default='*', help_text='Meses donde se iniciará la ejecución. Deben ser números entre el 1 (Enero) y el 12 (Diciembre) separados por comas.', max_length=255, verbose_name='Meses')),
                ('day_of_week', models.CharField(default='*', help_text='Días de la semana donde se iniciará la ejecución. Deben ser números entre el 1 (Lunes) y el 7 (Domingo) separados por comas.', max_length=255, verbose_name='Día de la semana')),
                ('year', models.CharField(default='*', help_text='Años donde se iniciará la ejecución. Deben ser un número de 4 dígitos.', max_length=255, verbose_name='Años')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='cron.job')),
            ],
        ),
    ]
