# Generated by Django 4.2.4 on 2023-08-26 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cron', '0003_alter_job_options_alter_jobschedule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobschedule',
            name='minute',
            field=models.CharField(default='0', help_text='Minutos donde se iniciará la ejecución. Deben ser números entre el 0 y el 59 separados por comas.', max_length=255, verbose_name='Minutos'),
        ),
    ]
