# Generated by Django 4.2.4 on 2023-08-26 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cron', '0004_alter_jobschedule_minute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='job',
            name='script',
            field=models.CharField(max_length=200, unique=True, verbose_name='Fichero'),
        ),
    ]
